version: '3'
services:
  web:
    build: .
    links:
      - db:mysql
    ports:
     - "5000:5000"
    volumes:
      - /opt/docker-compose-mysql:/counter_app
    container_name: counterapp_web_1
    depends_on:
      - db
  db:
    image: mysql:5.7.6
    restart: always
    container_name: counterapp_db_1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: GBA
